name: Unit Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout the repo
      - run: npm ci # install packages
      - run: npm test # run tests (configured to use jest-junit reporter)

# on: [pull_request]

# jobs:
#   tests:
#     runs-on: ubuntu-latest

#     stratergy:
#     matrix:
#       node-version: [19.x, 18.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{matrix.node-version}}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{matrix.node-version}}
#       - name: npm install
#          run: npm ci
#       - name: tests
#          run: npm test

